
import React from 'react';
import { StockAnalysis, InvestmentAction, RiskLevel } from '../types';
import { MetricCard } from './MetricCard';
import { TrendingUp, TrendingDown, AlertTriangle, CheckCircle, Info, ExternalLink, Download, ArrowRightCircle } from 'lucide-react';

interface AnalysisReportProps {
  analysis: StockAnalysis;
}

export const AnalysisReport: React.FC<AnalysisReportProps> = ({ analysis }) => {
  const getActionStyles = (action: InvestmentAction) => {
    switch (action) {
      case InvestmentAction.BUY: 
        return {
          color: 'text-emerald-400',
          bg: 'bg-emerald-400/10',
          border: 'border-emerald-400/20',
          label: 'BUY SIGNAL'
        };
      case InvestmentAction.HOLD: 
        return {
          color: 'text-amber-400',
          bg: 'bg-amber-400/10',
          border: 'border-amber-400/20',
          label: 'HOLD / NEUTRAL'
        };
      case InvestmentAction.SELL: 
        return {
          color: 'text-rose-500',
          bg: 'bg-rose-500/10',
          border: 'border-rose-500/30',
          label: 'SELL / EXIT'
        };
      case InvestmentAction.AVOID: 
        return {
          color: 'text-slate-400',
          bg: 'bg-slate-400/10',
          border: 'border-slate-400/20',
          label: 'AVOID / STAY AWAY'
        };
    }
  };

  const getRiskColor = (risk: RiskLevel) => {
    switch (risk) {
      case RiskLevel.LOW: return 'text-emerald-400';
      case RiskLevel.MEDIUM: return 'text-amber-400';
      case RiskLevel.HIGH: return 'text-rose-400';
    }
  };

  const styles = getActionStyles(analysis.action);

  const downloadReport = () => {
    const reportText = `
ARTHAAI INVESTMENT REPORT: ${analysis.companyName} (${analysis.symbol})
Date: ${new Date().toLocaleDateString()}

DECISION: ${analysis.action}
RISK LEVEL: ${analysis.riskLevel}
CONFIDENCE: ${analysis.confidenceScore}%
CURRENT PRICE: ₹${analysis.currentPrice}

THESIS:
${analysis.summary}
... [Report generated by ArthaAI] ...
    `;
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${analysis.symbol}_Analysis.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Action Header */}
      <div className={`p-8 rounded-2xl glass-card border-2 ${styles.border} relative overflow-hidden`}>
        <div className={`absolute top-0 right-0 w-32 h-32 ${styles.bg} rounded-full -mr-16 -mt-16 blur-3xl opacity-50`} />
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 relative z-10">
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <h2 className="text-4xl font-black text-white tracking-tight">{analysis.companyName}</h2>
              <span className="text-slate-500 font-mono text-lg bg-slate-900 px-3 py-1 rounded-lg border border-slate-800">{analysis.symbol}</span>
            </div>
            
            <div className="flex flex-wrap items-center gap-4">
              <div className={`flex items-center gap-2 px-6 py-2 rounded-xl border-2 font-black text-lg ${styles.color} ${styles.bg} ${styles.border}`}>
                <ArrowRightCircle size={20} />
                {styles.label}
              </div>
              <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-900/50 rounded-lg">
                <span className="text-slate-500 text-xs font-bold uppercase tracking-wider">Risk:</span>
                <span className={`font-bold ${getRiskColor(analysis.riskLevel)}`}>{analysis.riskLevel}</span>
              </div>
              <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-900/50 rounded-lg">
                <span className="text-slate-500 text-xs font-bold uppercase tracking-wider">Confidence:</span>
                <span className="font-bold text-blue-400">{analysis.confidenceScore}%</span>
              </div>
            </div>
          </div>
          
          <div className="flex flex-col items-end gap-3">
            <div className="text-right">
              <p className="text-slate-500 text-[10px] uppercase font-black tracking-[0.2em] mb-1">Live CMP</p>
              <p className="text-4xl font-black text-white tabular-nums">₹{analysis.currentPrice.toLocaleString('en-IN')}</p>
            </div>
            <button 
              onClick={downloadReport}
              className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-blue-900/20 active:scale-95"
            >
              <Download size={18} />
              Export PDF Report
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          {/* Summary */}
          <section className="space-y-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-blue-500 rounded-full" />
              <h3 className="text-xl font-black text-white uppercase tracking-tight">Investment Thesis</h3>
            </div>
            <div className="text-slate-300 text-lg leading-relaxed bg-slate-800/20 p-6 rounded-2xl border border-slate-700/50 italic">
              "{analysis.summary}"
            </div>
          </section>

          {/* Fundamentals */}
          <section className="space-y-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-emerald-500 rounded-full" />
              <h3 className="text-xl font-black text-white uppercase tracking-tight">Core Ratios</h3>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <MetricCard label="P/E Ratio" value={analysis.fundamentals.peRatio} description="Sector vs Company" />
              <MetricCard label="ROE" value={analysis.fundamentals.roe} suffix="%" description="Equity Return" />
              <MetricCard label="ROCE" value={analysis.fundamentals.roce} suffix="%" description="Capital Efficiency" />
              <MetricCard label="Debt/Eq" value={analysis.fundamentals.debtToEquity} description="Leverage" />
              <MetricCard label="Op. Margin" value={analysis.fundamentals.operatingMargin} suffix="%" description="Profitability" />
              <MetricCard label="Promoter" value={analysis.fundamentals.promoterHolding} suffix="%" description="Skin in the Game" />
              <MetricCard label="FII/DII" value={analysis.fundamentals.institutionalHolding} suffix="%" description="Smart Money" />
              <MetricCard label="P/B Ratio" value={analysis.fundamentals.pbRatio} description="Asset Pricing" />
            </div>
          </section>

          {/* Technicals */}
          <section className="space-y-4">
             <div className="flex items-center gap-2">
              <div className="w-8 h-1 bg-purple-500 rounded-full" />
              <h3 className="text-xl font-black text-white uppercase tracking-tight">Market Timing</h3>
            </div>
            <div className="p-8 rounded-2xl glass-card space-y-6 border-t-4 border-purple-500/30">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-2">
                   <p className="text-slate-500 text-xs font-black uppercase tracking-widest">Entry Strategy</p>
                   <p className="text-2xl font-black text-emerald-400">₹{analysis.suggestedEntryRange}</p>
                </div>
                <div className="space-y-2">
                   <p className="text-slate-500 text-xs font-black uppercase tracking-widest">Price Action</p>
                   <p className="text-2xl font-black text-white uppercase tracking-tighter">{analysis.technicals.trend}</p>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-6 border-t border-slate-700/50">
                <div className="space-y-3">
                  <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.2em]">Support (Buy Floor)</p>
                  <div className="flex flex-wrap gap-2">
                    {analysis.technicals.supportLevels.map(lvl => (
                      <span key={lvl} className="px-3 py-1.5 bg-emerald-500/5 text-emerald-400 rounded-lg border border-emerald-500/20 font-bold">₹{lvl}</span>
                    ))}
                  </div>
                </div>
                <div className="space-y-3">
                  <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.2em]">Resistance (Sell Ceiling)</p>
                  <div className="flex flex-wrap gap-2">
                    {analysis.technicals.resistanceLevels.map(lvl => (
                      <span key={lvl} className="px-3 py-1.5 bg-rose-500/5 text-rose-500 rounded-lg border border-rose-500/20 font-bold">₹{lvl}</span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* Action Panel */}
        <div className="space-y-6">
          <div className="p-8 rounded-3xl glass-card border border-emerald-500/20 relative group overflow-hidden">
            <div className="absolute inset-0 bg-emerald-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
            <h4 className="text-emerald-400 font-black text-sm uppercase tracking-[0.3em] mb-6 flex items-center gap-2">
              <TrendingUp size={16} /> Key Catalysts
            </h4>
            <ul className="space-y-4">
              {analysis.pros.map((pro, i) => (
                <li key={i} className="flex gap-4 text-slate-200">
                  <div className="mt-1.5 min-w-[6px] h-[6px] rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]" />
                  <span className="text-sm font-medium">{pro}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="p-8 rounded-3xl glass-card border border-rose-500/20 relative group overflow-hidden">
             <div className="absolute inset-0 bg-rose-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
            <h4 className="text-rose-400 font-black text-sm uppercase tracking-[0.3em] mb-6 flex items-center gap-2">
              <TrendingDown size={16} /> Risk Factors
            </h4>
            <ul className="space-y-4">
              {analysis.cons.map((con, i) => (
                <li key={i} className="flex gap-4 text-slate-200">
                  <div className="mt-1.5 min-w-[6px] h-[6px] rounded-full bg-rose-500 shadow-[0_0_8px_rgba(244,63,94,0.8)]" />
                  <span className="text-sm font-medium">{con}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="p-6 rounded-2xl bg-blue-600/10 border border-blue-500/30">
             <p className="text-[11px] text-blue-300 font-bold uppercase tracking-widest text-center mb-3">Model Grounding</p>
             <div className="space-y-2">
               {analysis.sources.map((s, i) => (
                 <a key={i} href={s.url} target="_blank" className="flex items-center justify-between text-[10px] text-slate-400 hover:text-white transition-colors">
                   <span className="truncate max-w-[150px]">{s.title}</span>
                   <ExternalLink size={10} />
                 </a>
               ))}
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};
